// esbuild inject file for the production neural-map bundle.
//
// esbuild's --inject feature replaces bare global variable reads with imports
// from this file.  The IIFE in neural-map.js ends with `}( THREE ) )`, where
// the outer `THREE` is a global reference.  esbuild replaces that reference
// with the imported THREE below, bundling Three.js directly into the output
// IIFE.  The result has no window.THREE dependency in production.
//
// For SCRIPT_DEBUG / fresh-checkout loads, three.min.js (generated by
// `npm run vendor:three`) continues to set window.THREE so that the IIFE
// source can be loaded directly without a prior build.
import * as THREE from 'three';
export { THREE };
